### ISSUE TITLE
Why did this project split from sympy?

### ISSUE THREAD

**Issue by j2kun** [diofant/diofant#1254]
Hi there,

I read the [about page](https://diofant.readthedocs.io/en/latest/aboutus.html) and I'm curious what prompted the fork of Sympy. What were the differences between the two projects, and what are the advantages of using this library over Sympy? Are there specific features or limitations I should expect?

**Comment by skirpichev** [comment]
> I read the [about page](https://diofant.readthedocs.io/en/latest/aboutus.html) and I'm curious what prompted the fork of Sympy.

Some more emotional remarks were removed from the page.  Feel free to dig the page history.  In short, the fork was started due to my personal view about the development of the SymPy.

> What were the differences between the two projects (1), and what are the advantages of using this library over Sympy (2)?

1. I'm not sure I'm able to describe the differences, see release notes, see also diofant/diofant#1028.
2. I don't know.

> Are there specific features or limitations I should expect?

I my view, it's to easy to include new code in the SymPy.  You can take look on the series module.  The SymPy tends to add more and more workarounds to support almost same set of limit examples.

Please reopen bug if you have more questions.
