### ISSUE TITLE
Float from float fails

### ISSUE THREAD

**Issue by cbm755** [diofant/diofant#676]
```py
>>> Float(1.1)
~/src/diofant.git/diofant/core/numbers.py in __new__(cls, num, dps)
    672         elif isinstance(num, float) and num == 0:
    673             num = '0'
--> 674         elif isinstance(num, (DIOFANT_INTS, Integer)):
    675             num = str(num)  # faster than mlib.from_int
    676         elif num is oo:

TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by skirpichev** [comment]
@cbm755, thank you.  It seems, this is not valid in the current master:
```
>>> from diofant import Float
>>> Float(1.1)
1.10000000000000
>>> from diofant import __version__
>>> __version__
'0.10.0.dev0'
```

**Comment by skirpichev** [comment]
Oh, I see, the problem is that git version require gmpy2>=2.1.0, which doesn't released yet (second alpha currently).  You can install optional "gmpy" dependency with pip, adding ``--pre`` argument, like our travis script did:
```
pip install --pre -U 'gmpy2;platform_python_implementation!="PyPy"'
```

Probably, this optional dependency was pre-installed on your system.  I'll correct minimal requirements for gmpy2 in compatibility.py, so it will fallback to python int's in this case.

@cbm755, thank you for catching this.  I would prefer to have requirements be specified in one place, but I don't know how to do this.

**Comment by cbm755** [comment]
Yes I I think I have 2.0.8 on Fedora 28.  Now on master I get:
```py
>>> from diofant import *
/home/cbm/src/diofant.git/diofant/external/importtools.py:122: UserWarning: gmpy2 version is too old to use (2.1.0 or newer required)
  UserWarning)

>>> Float(1.1)
1.10000000000000
```
So it is indeed falling back.

**Comment by skirpichev** [comment]
Unfortunately, changes related to gmpy2==2.1.0 - were reverted (apparently, new version of the gmpy2 aren't coming soon).

BTW, there are [0.10.0b1](https://pypi.org/project/Diofant/0.10.0b1/) beta version of the Diofant.  I would appreciate any testing.
